"""Initial models

Revision ID: 3c14c38d70df
Revises: 
Create Date: 2026-06-18 08:18:36.044432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c14c38d70df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstr2b_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_gstin', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('igst', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('hsn_codes', sa.JSON(), nullable=True),
    sa.Column('ims_status', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_image_path', sa.String(), nullable=True),
    sa.Column('ocr_raw_output', sa.JSON(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=True),
    sa.Column('extraction_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('gstr2b_record_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('reason_text_en', sa.String(), nullable=False),
    sa.Column('reason_text_hi', sa.String(), nullable=True),
    sa.Column('itc_impact_inr', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gstr2b_record_id'], ['gstr2b_records.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_table('invoices')
    op.drop_table('gstr2b_records')
    # ### end Alembic commands ###
