import React, { useState, useRef } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  TextInput,
  TouchableOpacity,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
  Animated,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
  Send,
  Sparkles,
  MessageCircleQuestion,
  BookOpen,
  ChevronDown,
  ChevronUp,
  IndianRupee,
  FileSpreadsheet,
  ShieldCheck,
  Scale,
  Receipt,
  CalendarClock,
  Mic,
  MicOff,
} from 'lucide-react-native';
import { Text } from '../components/AppText';
import { colors, typography, spacing, radii, elevation } from '../theme/tokens';
import { useI18n } from '../i18n/context';
import { askGstDoubt } from '../api/ai';
import { startRecording, stopRecordingAndTranscribe, isSttAvailable, translateToMarathi } from '../api/sarvam';

interface Msg {
  id: string;
  role: 'user' | 'ca';
  text: string;
  offline?: boolean;
}

interface LearnTopic {
  id: string;
  icon: React.ReactNode;
  title_en: string;
  title_hi: string;
  body_en: string;
  body_hi: string;
}

const LEARN_TOPICS: LearnTopic[] = [
  {
    id: 'itc',
    icon: <IndianRupee size={18} color={colors.primary} />,
    title_en: 'What is ITC?',
    title_hi: 'ITC क्या है?',
    body_en:
      'Input Tax Credit (ITC) is the tax you already paid on purchases. When you sell goods, you pay GST — but you can subtract the GST you paid on inputs. The difference is what you owe the government.\n\nExample: You buy goods worth ₹10,000 + ₹1,800 GST. You sell for ₹15,000 + ₹2,700 GST. You only pay ₹2,700 − ₹1,800 = ₹900 to the government.',
    body_hi:
      'Input Tax Credit (ITC) वो tax है जो आपने खरीदारी पर पहले ही चुकाया है। जब आप सामान बेचते हैं, तो GST लगता है — लेकिन आप inputs पर चुकाए गए GST को घटा सकते हैं। बाकी रकम सरकार को देनी होती है।\n\nउदाहरण: आपने ₹10,000 + ₹1,800 GST का सामान खरीदा। ₹15,000 + ₹2,700 GST में बेचा। सरकार को सिर्फ ₹2,700 − ₹1,800 = ₹900 देने हैं।',
  },
  {
    id: 'gstr2b',
    icon: <FileSpreadsheet size={18} color={colors.severity.pending} />,
    title_en: 'What is GSTR-2B?',
    title_hi: 'GSTR-2B क्या है?',
    body_en:
      'GSTR-2B is a monthly statement auto-generated by the GST portal around the 14th of each month. It lists all invoices your suppliers have filed — this is the data used to verify your ITC claims.\n\nThink of it as a "report card" of what your suppliers told the government. If an invoice is missing here, you cannot claim ITC on it.',
    body_hi:
      'GSTR-2B एक मासिक स्टेटमेंट है जो GST पोर्टल हर महीने की 14 तारीख को बनाता है। इसमें वो सारे बिल होते हैं जो आपके suppliers ने file किए हैं — इसी data से आपके ITC claims verify होते हैं।\n\nइसे ऐसे समझें: यह आपके suppliers का "report card" है। अगर कोई बिल यहाँ नहीं है, तो उस पर ITC claim नहीं होगा।',
  },
  {
    id: 'ims',
    icon: <ShieldCheck size={18} color={colors.severity.resolved} />,
    title_en: 'How does IMS work?',
    title_hi: 'IMS कैसे काम करता है?',
    body_en:
      'Invoice Management System (IMS) is mandatory since April 2026. Every invoice your supplier files appears on your IMS dashboard. You must choose:\n\n• Accept — invoice is correct, claim the ITC\n• Reject — something is wrong, do not claim\n• Hold — unsure, decide later\n\nImportant: if you do nothing, the system auto-accepts. For wrong invoices, inaction means you accept incorrect data.',
    body_hi:
      'Invoice Management System (IMS) अप्रैल 2026 से अनिवार्य है। आपके supplier का हर बिल आपके IMS dashboard पर आता है। आपको चुनना होगा:\n\n• Accept — बिल सही है, ITC claim करें\n• Reject — कुछ गलत है, claim न करें\n• Hold — पक्का नहीं, बाद में decide करें\n\nध्यान दें: अगर कुछ नहीं करते, तो system खुद Accept कर लेता है। गलत बिल पर कुछ न करना = गलत data Accept करना।',
  },
  {
    id: 'hsn',
    icon: <Receipt size={18} color={colors.primary} />,
    title_en: 'Why do HSN codes matter?',
    title_hi: 'HSN कोड क्यों ज़रूरी है?',
    body_en:
      'HSN (Harmonized System of Nomenclature) codes classify goods for tax purposes. Each product has a specific HSN code that determines its tax rate.\n\nIf your supplier files a wrong HSN code, the tax rate may be wrong — and your ITC gets blocked. This is one of the most common reasons for ITC mismatches.',
    body_hi:
      'HSN (Harmonized System of Nomenclature) कोड सामान को tax के लिए classify करते हैं। हर product का एक specific HSN कोड होता है जो उसका tax rate तय करता है।\n\nअगर supplier ने गलत HSN कोड डाला, तो tax rate गलत हो सकता है — और आपका ITC रुक जाता है। ITC mismatch का यह सबसे आम कारण है।',
  },
  {
    id: 'deadlines',
    icon: <CalendarClock size={18} color={colors.severity.pending} />,
    title_en: 'Key GST deadlines',
    title_hi: 'GST की मुख्य तारीखें',
    body_en:
      '• 11th of each month — GSTR-1 filing deadline (supplier files outward invoices)\n• 14th of each month — GSTR-2B generated (your reconciliation data)\n• 20th of each month — GSTR-3B filing deadline (your monthly return + tax payment)\n• September of next year — last date to claim ITC for a financial year (Section 16(4))\n\nMissing these means lost ITC or penalties.',
    body_hi:
      '• हर महीने की 11 तारीख — GSTR-1 filing deadline (supplier बाहर जाने वाले बिल file करता है)\n• हर महीने की 14 तारीख — GSTR-2B बनता है (आपका reconciliation data)\n• हर महीने की 20 तारीख — GSTR-3B filing deadline (मासिक return + tax भुगतान)\n• अगले साल सितंबर — किसी financial year का ITC claim करने की अंतिम तारीख (Section 16(4))\n\nये तारीखें छूटना = ITC का नुकसान या penalty।',
  },
  {
    id: 'blocked',
    icon: <Scale size={18} color={colors.severity.blocked} />,
    title_en: 'Section 17(5) — blocked credit',
    title_hi: 'Section 17(5) — blocked credit',
    body_en:
      'Some purchases can never have ITC claimed, regardless of valid invoices:\n\n• Motor vehicles (cars, bikes) — unless you are in the transport business\n• Food, beverages, outdoor catering\n• Membership of clubs, health & fitness centres\n• Travel benefits for employees (LTC)\n• Personal expenses billed to business\n\nThis app flags invoices that may fall in these categories — but always verify with your CA.',
    body_hi:
      'कुछ खरीदारी पर ITC कभी नहीं मिलता, चाहे बिल सही भी हो:\n\n• गाड़ी (car, bike) — जब तक आप transport व्यवसाय में न हों\n• खाना-पीना, outdoor catering\n• Club, health & fitness centre की membership\n• कर्मचारियों के travel benefits (LTC)\n• व्यक्तिगत खर्चे जो business में डाले गए हों\n\nयह app ऐसे बिल flag करता है — लेकिन हमेशा अपने CA से verify करें।',
  },
];

function LearnCard({ topic, lang }: { topic: LearnTopic; lang: 'hi' | 'en' | 'mr' }) {
  const [expanded, setExpanded] = useState(false);
  const rotation = useRef(new Animated.Value(0)).current;

  const toggle = () => {
    Animated.spring(rotation, {
      toValue: expanded ? 0 : 1,
      friction: 8,
      tension: 100,
      useNativeDriver: true,
    }).start();
    setExpanded(!expanded);
  };

  const rotate = rotation.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '180deg'],
  });

  return (
    <View style={styles.learnCard}>
      <TouchableOpacity
        style={styles.learnCardHeader}
        onPress={toggle}
        activeOpacity={0.7}
      >
        <View style={styles.learnCardIcon}>{topic.icon}</View>
        <Text style={styles.learnCardTitle}>
          {lang === 'hi' ? topic.title_hi : topic.title_en}
        </Text>
        <Animated.View style={{ transform: [{ rotate }] }}>
          <ChevronDown size={18} color={colors.inkMuted} />
        </Animated.View>
      </TouchableOpacity>
      {expanded && (
        <View style={styles.learnCardBody}>
          <Text style={styles.learnCardText}>
            {lang === 'hi' ? topic.body_hi : topic.body_en}
          </Text>
        </View>
      )}
    </View>
  );
}

export default function AskCaScreen() {
  const { t, lang } = useI18n();
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Msg[]>([]);
  const [busy, setBusy] = useState(false);
  const [recording, setRecording] = useState(false);
  const [activeTab, setActiveTab] = useState<'learn' | 'ask'>('ask');
  const scrollRef = useRef<ScrollView>(null);

  const handleMic = async () => {
    if (recording) {
      try {
        setRecording(false);
        const transcript = await stopRecordingAndTranscribe(lang);
        if (transcript.trim()) setInput((prev) => (prev ? prev + ' ' : '') + transcript.trim());
      } catch {
        // silently fail — user can still type
      }
    } else {
      try {
        await startRecording();
        setRecording(true);
      } catch {
        // permission denied or device unsupported
      }
    }
  };

  const send = async (questionText?: string) => {
    const question = (questionText ?? input).trim();
    if (!question || busy) return;

    setActiveTab('ask');
    const userMsg: Msg = { id: `u-${Date.now()}`, role: 'user', text: question };
    setMessages((m) => [...m, userMsg]);
    setInput('');
    setBusy(true);
    setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 50);

    try {
      // Ask in Hindi (Gemini handles hi/en well); translate to Marathi if needed.
      const queryLang = lang === 'mr' ? 'hi' : lang;
      const { answer, method } = await askGstDoubt(question, queryLang);
      let finalAnswer = answer;
      if (lang === 'mr') {
        try { finalAnswer = await translateToMarathi(answer, 'hi'); } catch { /* use original */ }
      }
      setMessages((m) => [
        ...m,
        { id: `c-${Date.now()}`, role: 'ca', text: finalAnswer, offline: method === 'fallback' },
      ]);
    } catch {
      const errorTexts: Record<string, string> = {
        hi: 'अभी जवाब नहीं मिल पाया। Server चालू है या नहीं जांचें।',
        en: "Couldn't reach the assistant. Check that the AI server is running.",
        mr: 'सध्या उत्तर मिळू शकले नाही. Server चालू आहे का ते तपासा.',
      };
      setMessages((m) => [
        ...m,
        { id: `c-${Date.now()}`, role: 'ca', text: errorTexts[lang] ?? errorTexts.en, offline: true },
      ]);
    } finally {
      setBusy(false);
      setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 50);
    }
  };

  const showGreeting = messages.length === 0 && activeTab === 'ask';
  const showLearn = activeTab === 'learn' && messages.length === 0;

  return (
    <View style={styles.root}>
      <View style={styles.header}>
        <SafeAreaView edges={['top']}>
          <View style={styles.headerRow}>
            <View style={styles.headerIcon}>
              <MessageCircleQuestion size={22} color={colors.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.headerTitle}>{t.askCa.title}</Text>
              <Text style={styles.headerSub}>{t.askCa.subtitle}</Text>
            </View>
          </View>

          {/* Tab switcher — Learn / Ask */}
          {messages.length === 0 && (
            <View style={styles.tabRow}>
              <TouchableOpacity
                style={[styles.tab, activeTab === 'learn' && styles.tabActive]}
                onPress={() => setActiveTab('learn')}
                activeOpacity={0.7}
              >
                <BookOpen size={14} color={activeTab === 'learn' ? colors.primary : colors.inkMuted} />
                <Text style={[styles.tabText, activeTab === 'learn' && styles.tabTextActive]}>
                  {lang === 'hi' ? 'सीखें' : 'Learn'}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.tab, activeTab === 'ask' && styles.tabActive]}
                onPress={() => setActiveTab('ask')}
                activeOpacity={0.7}
              >
                <MessageCircleQuestion size={14} color={activeTab === 'ask' ? colors.primary : colors.inkMuted} />
                <Text style={[styles.tabText, activeTab === 'ask' && styles.tabTextActive]}>
                  {lang === 'hi' ? 'सवाल पूछें' : 'Ask'}
                </Text>
              </TouchableOpacity>
            </View>
          )}
        </SafeAreaView>
      </View>

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 90 : 0}
      >
        <ScrollView
          ref={scrollRef}
          style={styles.flex}
          contentContainerStyle={styles.chat}
          showsVerticalScrollIndicator={false}
        >
          {/* Learn tab content */}
          {showLearn && (
            <>
              <View style={styles.learnHero}>
                <BookOpen size={24} color={colors.primary} />
                <Text style={styles.learnHeroTitle}>
                  {lang === 'hi' ? 'GST की बुनियादी बातें' : 'GST Basics'}
                </Text>
                <Text style={styles.learnHeroSub}>
                  {lang === 'hi'
                    ? 'ITC, GSTR-2B, IMS — सब कुछ आसान भाषा में समझें'
                    : 'Understand ITC, GSTR-2B, IMS — explained simply'}
                </Text>
              </View>

              {LEARN_TOPICS.map((topic) => (
                <LearnCard key={topic.id} topic={topic} lang={lang} />
              ))}

              <View style={styles.learnFooter}>
                <Text style={styles.learnFooterText}>
                  {lang === 'hi'
                    ? 'कोई और सवाल है? "सवाल पूछें" tab पर जाएं'
                    : 'Have more questions? Switch to the "Ask" tab'}
                </Text>
              </View>
            </>
          )}

          {/* Ask tab — greeting + suggestions */}
          {showGreeting && (
            <>
              <View style={styles.greetingCard}>
                <Sparkles size={18} color={colors.primary} />
                <Text style={styles.greetingText}>{t.askCa.greeting}</Text>
              </View>
              <Text style={styles.faqTitle}>{t.askCa.faqTitle}</Text>
              <Text style={styles.faqHint}>{t.askCa.faqHint}</Text>
              <View style={styles.suggestions}>
                {[t.askCa.suggestion1, t.askCa.suggestion2, t.askCa.suggestion3, t.askCa.suggestion4].map((s) => (
                  <TouchableOpacity key={s} style={styles.suggestionChip} onPress={() => send(s)} activeOpacity={0.8}>
                    <MessageCircleQuestion size={16} color={colors.primary} />
                    <Text style={styles.suggestionText}>{s}</Text>
                  </TouchableOpacity>
                ))}
              </View>
            </>
          )}

          {/* Chat messages */}
          {messages.map((m) =>
            m.role === 'user' ? (
              <View key={m.id} style={styles.userBubble}>
                <Text style={styles.userText}>{m.text}</Text>
              </View>
            ) : (
              <View key={m.id} style={styles.caBubble}>
                <Text style={styles.caText}>{m.text}</Text>
                {m.offline && <Text style={styles.offlineNote}>{t.askCa.offlineNote}</Text>}
              </View>
            ),
          )}

          {busy && (
            <View style={styles.caBubble}>
              <View style={styles.thinkingRow}>
                <ActivityIndicator size="small" color={colors.primary} />
                <Text style={styles.thinkingText}>{t.askCa.thinking}</Text>
              </View>
            </View>
          )}
        </ScrollView>

        <View style={styles.inputBar}>
          {isSttAvailable() && (
            <TouchableOpacity
              style={[styles.micButton, recording && styles.micButtonActive]}
              onPress={handleMic}
              activeOpacity={0.75}
              accessibilityRole="button"
              accessibilityLabel={recording ? 'Stop recording' : 'Start voice input'}
            >
              {recording ? <MicOff size={20} color="#FFFFFF" /> : <Mic size={20} color={colors.primary} />}
            </TouchableOpacity>
          )}
          <TextInput
            style={styles.input}
            value={input}
            onChangeText={setInput}
            placeholder={t.askCa.placeholder}
            placeholderTextColor={colors.inkMuted}
            multiline
            onSubmitEditing={() => send()}
            onFocus={() => setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 300)}
          />
          <TouchableOpacity
            style={[styles.sendButton, (!input.trim() || busy) && styles.sendButtonDisabled]}
            onPress={() => send()}
            disabled={!input.trim() || busy}
            activeOpacity={0.85}
          >
            <Send size={20} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  header: {
    backgroundColor: colors.background,
    paddingHorizontal: spacing.screenH,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.sm },
  headerIcon: {
    width: 44, height: 44, borderRadius: 14,
    backgroundColor: colors.surfaceRaised,
    justifyContent: 'center', alignItems: 'center',
  },
  headerTitle: { fontSize: 20, fontWeight: '800', color: colors.ink },
  headerSub: { ...typography.caption, color: colors.inkMuted, marginTop: 2 },

  // Tab switcher
  tabRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabActive: {
    backgroundColor: colors.accentMuted,
    borderColor: colors.primary,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.inkMuted,
  },
  tabTextActive: {
    color: colors.primary,
  },

  // Learn section
  learnHero: {
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.lg,
  },
  learnHeroTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.ink,
  },
  learnHeroSub: {
    ...typography.body,
    color: colors.inkMuted,
    textAlign: 'center',
  },
  learnCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    overflow: 'hidden',
  },
  learnCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
  },
  learnCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.surfaceRaised,
    justifyContent: 'center',
    alignItems: 'center',
  },
  learnCardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.ink,
  },
  learnCardBody: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  learnCardText: {
    ...typography.body,
    color: colors.inkSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  learnFooter: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  learnFooterText: {
    ...typography.caption,
    color: colors.inkMuted,
    textAlign: 'center',
  },

  // Chat area
  chat: { padding: spacing.screenH, gap: spacing.md, paddingBottom: spacing.lg },
  greetingCard: {
    flexDirection: 'row',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  greetingText: { ...typography.body, color: colors.inkSecondary, flex: 1 },
  faqTitle: { ...typography.heading2, color: colors.ink, marginTop: spacing.lg },
  faqHint: { ...typography.caption, color: colors.inkMuted, marginBottom: spacing.sm },
  suggestions: { gap: spacing.sm },
  suggestionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radii.button,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  suggestionText: { ...typography.body, color: colors.primary, fontWeight: '600', flex: 1 },

  userBubble: {
    alignSelf: 'flex-end',
    maxWidth: '85%',
    backgroundColor: colors.primary,
    borderRadius: radii.card,
    borderBottomRightRadius: 4,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  userText: { ...typography.body, color: '#FFFFFF' },
  caBubble: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    borderBottomLeftRadius: 4,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  caText: { ...typography.body, color: colors.ink },
  offlineNote: { ...typography.caption, color: colors.inkMuted, marginTop: spacing.sm, fontStyle: 'italic' },
  thinkingRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  thinkingText: { ...typography.body, color: colors.inkMuted },

  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
    paddingHorizontal: spacing.screenH,
    paddingVertical: spacing.sm,
    paddingBottom: Platform.OS === 'ios' ? spacing.lg : spacing.sm,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  input: {
    flex: 1,
    ...typography.body,
    color: colors.ink,
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.input,
    paddingHorizontal: spacing.md,
    paddingTop: 10,
    paddingBottom: 10,
    maxHeight: 120,
  },
  micButton: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: colors.surfaceRaised,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  micButtonActive: {
    backgroundColor: colors.severity.blocked,
    borderColor: colors.severity.blocked,
  },
  sendButton: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: colors.primary,
    justifyContent: 'center', alignItems: 'center',
    ...elevation.primary,
  },
  sendButtonDisabled: { backgroundColor: colors.surfaceRaised, shadowOpacity: 0 },
});
